name: Release

on:
  workflow_run:
    workflows: ['Add Partytown']
    types:
      - completed

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
